server:
  port: ${config.server.port}

spring:
  # application
  application:
    name: entertainment

  # config
  config:
    import: optional:configserver:http://localhost:8071

  # cloud
  cloud:
    config:
      uri: http://localhost:8071
      name: config
      profile: entertainment
      fail-fast: true
      enabled: true
      username: admin
      password: Teste@123

  # actuator
  management:
    endpoints:
      web:
        exposure:
          include: env

  # database
  datasource:
    url: jdbc:postgresql://${config.db.host}:${config.db.port}/${config.db.name}
    username: ${config.db.user}
    password: ${config.db.password}
    driver-class-name: org.postgresql.Driver
    #hikari:
      #maximum-pool-size: 10
      #minimum-idle: 5

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # jwt
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${config.jwt.secret}

  # MultipartFile
  servlet:
    multipart:
      max-file-size: 6GB
      max-request-size: 6GB