spring:
  # application
  application:
    name: entertainment

  # database
  datasource:
    url: jdbc:postgresql://localhost:5432/db_entertainment
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    #hikari:
      #maximum-pool-size: 10
      #minimum-idle: 5

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # jwt
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "your-long-secret-key-that-has-32-or-more-characters"